# Generated by Django 4.1.1 on 2022-09-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0003_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('RUB', 'rub')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
