# Generated by Django 4.1.1 on 2022-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0004_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('rub', 'RUB')], max_length=3),
        ),
    ]
