# Generated by Django 4.1.1 on 2022-09-11 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0009_discount_order_discounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название налога')),
                ('inclusive', models.BooleanField(verbose_name='Является ли ставка налога включенной или исключающей')),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент налога')),
            ],
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent_off',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(to='OrdersApp.tax', verbose_name='Налоги'),
        ),
    ]
