# Generated by Django 4.1.1 on 2022-09-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0010_tax_alter_discount_percent_off_order_taxes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB')], max_length=3, verbose_name='Валюта оформления заказа'),
        ),
    ]
