# Generated by Django 4.1.1 on 2022-09-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0011_rename_discription_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(blank=True, null=True, to='OrdersApp.discount', verbose_name='Купоны'),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, null=True, to='OrdersApp.tax', verbose_name='Налоги'),
        ),
    ]
