# Generated by Django 4.1.1 on 2022-09-11 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0012_alter_order_discounts_alter_order_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='duration_in_months',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='OrdersApp.discount', verbose_name='Купоны'),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='OrdersApp.tax', verbose_name='Налоги'),
        ),
    ]
